[workspace]

members = [
    "src/geonft",
    "src/geonft_shared",
    "src/geonft_wasm",
    "src/geonft_solana",
    "src/sync-bot",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"


