[package]
name = "geonft"
version = "0.1.0"
authors = ["Brian Anderson <andersrb@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
include_dir = "0.6.0"
rocket = "0.4.7"

[dependencies.rocket_contrib]
version = "0.4.7"
default-features = false
features = ["tera_templates"]
